### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by prydie** [torchbox/wagtail-cookiecutter#9]
The following error is produced when running `vagrant up` after changing the requirements file to specify

```
Django==1.8.2
wagtail==1.0b2
```

```
==> default:   Applying home.0002_create_homepage...
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/models/query.py", line 405, in get_or_create
==> default:     return self.get(**lookup), False
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/models/query.py", line 334, in get
==> default:     self.model._meta.object_name
==> default: __fake__.DoesNotExist: ContentType matching query does not exist.
==> default:
==> default: During handling of the above exception, another exception occurred:
==> default:
==> default: Traceback (most recent call last):
==> default:   File "/vagrant/manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
==> default:     self.fetch_command(subcommand).run_from_argv(self.argv)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
==> default:     self.execute(*args, **cmd_options)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
==> default:     output = self.handle(*args, **options)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 221, in handle
==> default:     executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
==> default:     self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
==> default:     state = migration.apply(state, schema_editor)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
==> default:     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
==> default:     self.code(from_state.apps, schema_editor)
==> default:   File "/vagrant/wagtailproj/home/migrations/0002_create_homepage.py", line 19, in create_homepage
==> default:     model='homepage', app_label='home', defaults={'name': 'Homepage'})
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/models/manager.py", line 127, in manager_method
==> default:     return getattr(self.get_queryset(), name)(*args, **kwargs)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/models/query.py", line 407, in get_or_create
==> default:     return self._create_object_from_params(lookup, params)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
==> default:     obj = self.create(**params)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/models/query.py", line 346, in create
==> default:     obj = self.model(**kwargs)
==> default:   File "/home/vagrant/.virtualenvs/wagtailproj/lib/python3.4/site-packages/django/db/models/base.py", line 480, in __init__
==> default:     raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
==> default: TypeError: 'name' is an invalid keyword argument for this function
```

**Comment by khanhhua** [comment]
I have the same issue (even outside the vagrant box). Could this be a wagtail issue?

**Comment by gasman** [comment]
This happens because one of the Django built-in models (contenttype, IIRC) has had its definition changed in Django 1.8 to remove the 'name' field - the migration will need to be updated accordingly.

**Comment by kaedroho** [comment]
I'll rebuild the cookiecutter on top of the builtin template once it's merged (this supports Django 1.8).

https://github.com/torchbox/wagtail/pull/1109

**Comment by zerolab** [comment]
FYI, https://github.com/torchbox/wagtail/pull/1109 has been merged.

For existing projects, edit `home.0002_create_homepage` and remove the name parameter in `ContentType.objects.get_or_create()`.

**Comment by kaedroho** [comment]
Django 1.8 support added into 2.5.0
